### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by cytheworkhorse** [cytheworkhorse/rustbox#2]
- [ ] Add prompt operation
- [x] Add intensity options
- [x] Add main loop
